### ISSUE TITLE
README fix required

### ISSUE THREAD

**Issue by smetj** [confluentinc/kafka-packaging#4]
The readme contains a typo:
```
git remote add upstream upstream http://git-wip-us.apache.org/repos/asf/kafka.git
```
should be
```
git remote add upstream http://git-wip-us.apache.org/repos/asf/kafka.git
```

**Comment by ewencp** [comment]
@smetj Fixed that up. You may also want to take a look at https://github.com/confluentinc/packaging which is the repository that ties all our packaging together. I'm not sure I've kept all the READMEs up to date, so that might be a better reference for how things get built (and includes scripts to handle running stuff in VMs, which is also convenient).
